# Generated by Django 4.2.16 on 2024-11-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField(blank=True)),
                ('spcl_cnd', models.TextField(blank=True)),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField(blank=True)),
                ('etc_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=10, unique=True)),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
                ('cur_nm', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField(blank=True)),
                ('spcl_cnd', models.TextField(blank=True)),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField(blank=True)),
                ('etc_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.savingproduct')),
                ('registered_user', models.ManyToManyField(related_name='registered_saving_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.depositproduct')),
                ('registered_user', models.ManyToManyField(related_name='registered_deposit_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
